server:
  port: 8081
  mode: dev
  jwt_secret_key: secretkey
  jwt_exp_time_min: 5
  jwt_refresh_secret_key: refreshsecretkey
  jwt_refresh_exp_time_hour: 360

logger:
  level: info

postgres:
  host: localhost
  port: 5432
  username: postgres
  password: root
  db_name: study_platform