server:
  rest_port: 8081
  ws_port: 8082
  mode: dev
  jwt_secret_key: secretkey
  jwt_exp_time_min: 5
  ws_jwt_secret_key: wssecretkey
  ws_jwt_exp_time_hour: 24
  jwt_refresh_secret_key: refreshsecretkey
  jwt_refresh_exp_time_hour: 360

logger:
  level: info

postgres:
  host: localhost
  port: 5432
  username: postgres
  password: root
  db_name: study_platform